WIN_WIDTH = 1200
WIN_HEIGHT = 800

# prevents infinite loops in node table building
MAX_NODES = 2000

NODE_TYPES = (
    "INVALID",
    "Message",
    "Branch",
    "Event",
    "Entry",
    "Jump",
)

PARAM_TYPES = (
    "s32",
    "s16, s16",
    "s16, s8, s8",
    "s8, s8, s16",
    "s8, s8, s8, s8",
    "string",
    "s32",
)

BRANCH_TYPES = (
    "unk_branch_00",
    "checkEnergyTank",
    "checkStoryProgress",
    "unk_branch_03",
    "checkGamemode",
    "unk_branch_05",
    "unk_branch_06",
    "unk_branch_07",
    "unk_branch_08",
    "checkDifficulty",
    "unk_branch_0a",
    "unk_branch_0b",
)

BRANCH_CONDITIONS = (
    ("unk0","unk1","unk2"),
    ("less_or_equal","greater"),
    ("less_or_equal","greater"),
    ("never","always"), # condition is always branch 1
    ("story","mission","versus"),
    ("unk0","unk1","unk2"),
    ("unk0","unk1","unk2"),
    ("unk0","unk1","unk2"),
    ("unk0","unk1","unk2"),
    ("normal", "spicy", "ultra_spicy"),
    ("unk0","unk1","unk2"),
    ("unk0","unk1","unk2"),
)

EVENT_TYPES = (
    "playDemo",
    "unk_event_01",
    "unk_event_02",
    "unk_event_03",
    "unk_event_04",
    "unk_event_05",
    "unk_event_06",
    "unk_event_07",
    "unk_event_08",
    "unk_event_09",
    "unk_event_0a",
    "unk_event_0b",
    "unk_event_0c",
    "unk_event_0d",
    "unk_event_0e",
    "unk_event_0f",
    "unk_event_10",
    "unk_event_11",
    "unk_event_12",
    "unk_event_13",
    "unk_event_14",
    "unk_event_15",
    "unk_event_16",
    "unk_event_17",
    "unk_event_18",
    "unk_event_19",
    "unk_event_1a",
    "unk_event_1b",
    "unk_event_1c",
    "unk_event_1d",
    "unk_event_1e",
    "setStoryProgress",
    "unlockKoppad",
    "unk_event_21",
    "unk_event_22",
    "unk_event_23",
    "unk_event_23",
    "unk_event_24",
    "unlockKoppadButton",
    "unk_event_26",
    "unk_event_27",
    "unk_event_28",
    "unk_event_29",
    "unk_event_2a",
    "unk_event_2b",
    "unk_event_2c",
    "unk_event_2d",
    "unk_event_2e",
    "unk_event_2f",
    "unk_event_30",
    "unk_event_31",
    "unk_event_32",
    "unk_event_33",
    "unk_event_34",
    "unk_event_35",
    "unk_event_36",
    "unk_event_37",
    "unk_event_38",
    "unk_event_39",
    "unk_event_3a",
    "unk_event_3b",
    "unk_event_3c",
    "unk_event_3d",
    "unk_event_3e",
    "unk_event_3f",
    "unk_event_40",
    "unk_event_41",
    "unk_event_42",
    "unk_event_43",
    "unk_event_44",
    "unk_event_45",
    "unk_event_46",
    "unk_event_47",
    "unk_event_48",
)